#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# build-app.sh — compile miniowl and wrap the binary in a .app bundle.
#
# Produces build/miniowl.app which can be copied to /Applications and
# launched like any other menu bar app. Ad-hoc signs with entitlements
# so Accessibility prompts display correctly.
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

cd "$(dirname "$0")/.."

# 0. Privacy gate — fail the build before we waste cycles compiling.
./scripts/check-privacy.sh

# 1. Compile release binary via SPM.
echo "building miniowl (release)..."
swift build -c release

BIN=".build/release/miniowl"
APP="build/miniowl.app"

if [[ ! -f "$BIN" ]]; then
  echo "error: expected binary at $BIN"
  exit 1
fi

# 2. Lay out the .app bundle skeleton.
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"
mkdir -p "$APP/Contents/Resources"

cp "$BIN" "$APP/Contents/MacOS/miniowl"
cp miniowl-bundle/Info.plist "$APP/Contents/Info.plist"

# Copy the app icon if it exists. Generated by `tools/make-icon.sh`
# and committed in-repo so a fresh clone doesn't need to regenerate it.
if [[ -f miniowl-bundle/AppIcon.icns ]]; then
  cp miniowl-bundle/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"
fi

# 3. Ad-hoc sign with entitlements. Ad-hoc signatures are stable for
#    a single developer machine — TCC grants survive as long as the
#    binary isn't moved. Switch to a real Developer ID identity later
#    if you want to share the app across machines.
codesign \
  --force \
  --sign - \
  --entitlements miniowl-bundle/miniowl.entitlements \
  --options runtime \
  "$APP"

echo ""
echo "built: $APP"
echo "size:  $(du -sh "$APP" | cut -f1)"
echo ""
echo "to install:  cp -R $APP /Applications/ && open /Applications/miniowl.app"
echo "to run dev:  open $APP"
