#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# build-app.sh — compile miniowl and wrap the binary in a .app bundle.
#
# Produces build/miniowl.app which can be copied to /Applications and
# launched like any other menu bar app.
#
# Code-signing identity is auto-detected with this preference order:
#   1. $MINIOWL_SIGNING_IDENTITY  (explicit override — use any string
#      `security find-identity -v -p codesigning` accepts, e.g.
#      "Developer ID Application: Your Name (TEAMID)")
#   2. First "Developer ID Application: …" cert in your keychain
#      (the proper macOS distribution cert — required to ship to
#      others without "unidentified developer" warnings; can be
#      issued from developer.apple.com if you have a paid Apple
#      Developer Program account)
#   3. First "Apple Development: …" cert in your keychain
#      (works fine for personal use on your own Mac, and gives a
#      *stable* TCC identity so the Accessibility grant survives
#      rebuilds — until the cert expires, ~1 year)
#   4. Ad-hoc signature ("- ") as a last resort — works but TCC
#      grants invalidate on every rebuild because the cdhash changes
#
# To force a specific identity:
#   MINIOWL_SIGNING_IDENTITY="Apple Development: Jane Doe (ABCD123456)" ./scripts/build-app.sh
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

cd "$(dirname "$0")/.."

# 0a. Parse flags.
#   --dev  → pass -DMINIOWL_DEV so CategorizationClient points at
#            localhost instead of production. Default = production build.
BUILD_FLAGS=()
BUILD_ENV_LABEL="production"
for arg in "$@"; do
  case "$arg" in
    --dev|-dev)
      BUILD_FLAGS+=("-Xswiftc" "-DMINIOWL_DEV")
      BUILD_ENV_LABEL="dev (localhost)"
      ;;
    *)
      echo "warning: unknown flag '$arg'" >&2
      ;;
  esac
done

# 0b. Privacy gate — fail the build before we waste cycles compiling.
./scripts/check-privacy.sh

# 1. Resolve a signing identity *before* compiling so we can fail
#    early if something is misconfigured.
resolve_signing_identity() {
  if [[ -n "${MINIOWL_SIGNING_IDENTITY:-}" ]]; then
    echo "$MINIOWL_SIGNING_IDENTITY"
    return 0
  fi

  local devid_app
  devid_app=$(security find-identity -v -p codesigning 2>/dev/null \
              | awk -F'"' '/Developer ID Application/ {print $2; exit}')
  if [[ -n "$devid_app" ]]; then
    echo "$devid_app"
    return 0
  fi

  local apple_dev
  apple_dev=$(security find-identity -v -p codesigning 2>/dev/null \
              | awk -F'"' '/Apple Development/ {print $2; exit}')
  if [[ -n "$apple_dev" ]]; then
    echo "$apple_dev"
    return 0
  fi

  echo "-"  # ad-hoc fallback
}

SIGN_IDENTITY=$(resolve_signing_identity)

case "$SIGN_IDENTITY" in
  "Developer ID Application:"*)
    SIGN_KIND="developer-id (distribution-grade)"
    ;;
  "Apple Development:"*)
    SIGN_KIND="apple-development (stable for personal use)"
    ;;
  "-")
    SIGN_KIND="ad-hoc (TCC grant will reset on every rebuild)"
    ;;
  *)
    SIGN_KIND="custom override"
    ;;
esac

echo "signing with: $SIGN_IDENTITY"
echo "      kind:   $SIGN_KIND"
echo ""

# 2. Compile release binary via SPM.
echo "building miniowl (release) [env: $BUILD_ENV_LABEL]..."
swift build -c release "${BUILD_FLAGS[@]}"

BIN=".build/release/miniowl"
APP="build/miniowl.app"

if [[ ! -f "$BIN" ]]; then
  echo "error: expected binary at $BIN"
  exit 1
fi

# 3. Lay out the .app bundle skeleton.
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"
mkdir -p "$APP/Contents/Resources"

cp "$BIN" "$APP/Contents/MacOS/miniowl"
cp miniowl-bundle/Info.plist "$APP/Contents/Info.plist"

# Copy the app icon if it exists. Generated by `tools/make-icon.sh`
# and committed in-repo so a fresh clone doesn't need to regenerate it.
if [[ -f miniowl-bundle/AppIcon.icns ]]; then
  cp miniowl-bundle/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"
fi

# 4. Sign with the resolved identity. --identifier locks in the bundle
#    ID at signing time so codesign doesn't have to derive it from the
#    Info.plist (defends against accidental ID drift across rebuilds).
codesign \
  --force \
  --sign "$SIGN_IDENTITY" \
  --identifier me.journely.miniowl \
  --entitlements miniowl-bundle/miniowl.entitlements \
  --options runtime \
  "$APP"

# 5. Verify the signature is valid before we hand the user a broken bundle.
codesign --verify --strict "$APP" 2>&1 || {
  echo "error: codesign --verify failed for $APP"
  exit 1
}

echo ""
echo "built: $APP"
echo "size:  $(du -sh "$APP" | cut -f1)"
echo ""
echo "to install:  cp -R $APP /Applications/ && open /Applications/miniowl.app"
echo "to run dev:  open $APP"
